### ISSUE TITLE
Whitespace after Street Name

### ISSUE THREAD

**Issue by thomaskonrad** [scubbx/convert-bev-address-data-python#1]
Hi,

a little "cosmetic defect" I came across when reviewing the output of the script: There's a whitespace after the street name in every row.

```
Eisenstadt;7000;Josef Stanislaus Albach-Gasse ;2;;16.524064;47.846659
Eisenstadt;7000;Josef Stanislaus Albach-Gasse ;4;;16.523809;47.846972
Eisenstadt;7000;Untere Kirchberggasse ;5;;16.50274;47.839414
```

Thanks for the quick development of the script after the BEV data release!

Thomas

**Comment by scubbx** [comment]
Right, this does not hurt but is unnecessary. Fixed.
