### ISSUE TITLE
default output coordinate system

### ISSUE THREAD

**Issue by nebulon42** [scubbx/convert-bev-address-data-python#6]
The readme states

> The coordinate system of the output file is the WGS84 system by default

However, a file `bev_addressesEPSG3035.csv` is produced without epsg parameter. [EPSG:3035](http://spatialreference.org/ref/epsg/etrs89-etrs-laea/) is not WGS84 or am I misunderstanding something?

System: Ubuntu 16.04, Python 3.5.2, python3-gdal 2.1.0

**Comment by scubbx** [comment]
Right, I forgot to change the readme.
Fixed by: d3108087a6b5ad8eefbaab0e6814f776eb4c7d35
