### ISSUE TITLE
Python 3 progress bar error

### ISSUE THREAD

**Issue by nebulon42** [scubbx/convert-bev-address-data-python#7]
When running with Python 3 I get the following error

````
File "convert-addresses.py", line 257, in <module>
    sys.stdout.write('[{}]'.format(('#' * (int(current_percentage) / 2)).ljust(50)))
TypeError: can't multiply sequence by non-int of type 'float'
````

Python 3.5.2

**Comment by scubbx** [comment]
The int() is not applied to the result of the devision of 'current_percentage' by '2' because of a wrongly set bracket.
Fixed by 16f2e7cfe9cd79a9d559cdbdbe2aff7d6e27bce3 , 9d3e609599ab928780c55790c44140faf4eb8228 and 2cf379b42879aa5d2f4c73a13574ad0777f82d07
